/* ========================= 1 - Database exploration ========================= */

-- Explore all objects in the DB
SELECT * FROM INFORMATION_SCHEMA.TABLES


-- Explore all columns in the DB
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'



/* ========================= 2 - Dimension exploration ========================= */

-- Explore all countries our customers come from
SELECT DISTINCT country FROM gold.dim_customers;

-- Explore all categories 'the major divisions'
SELECT DISTINCT 
	category, 
	subcategory, 
	product_name 
FROM gold.dim_products
ORDER BY 1,2,3;



/* ========================= 3 - Data Exploration ========================= */

-- Find the first and last order
-- How many years of sales are available?
SELECT 
	MIN(order_date) AS first_order_date,
	MAX(order_date) AS last_order_date,
	DATEDIFF(year, MIN(order_date), MAX(order_date)) AS order_range_years
FROM gold.fact_sales;

-- Find the youngest and the oldest customer
SELECT
	MIN(birthdate) AS oldest_customer,
	DATEDIFF(year, MIN(birthdate), GETDATE()) AS oldest_age,
	MAX(birthdate) AS youngest_customer,
	DATEDIFF(year, MAX(birthdate), GETDATE()) AS youngest_age
FROM gold.dim_customers;



/* ========================= 4 - Measures Exploration ========================= */

SELECT * FROM gold.fact_sales;

-- Find the total sales
SELECT
	SUM(sales_amount) AS total_sales
FROM gold.fact_sales;

-- Find how many items were sold
SELECT
	SUM(quantity) AS total_quantity
FROM gold.fact_sales;

-- Find the average selling price
SELECT
	AVG(price) AS avg_price
FROM gold.fact_sales;

-- Find the total number of orders
SELECT
	COUNT(order_number) AS total_orders
FROM gold.fact_sales;

SELECT
	COUNT(DISTINCT order_number) AS total_orders
FROM gold.fact_sales;

-- Find the total number of products
SELECT 
	COUNT(product_key) AS total_products
FROM gold.dim_products

SELECT 
	COUNT(DISTINCT product_key) AS total_products
FROM gold.dim_products

-- Find the total number of customers
SELECT
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers;

SELECT
	COUNT(DISTINCT customer_key) AS total_customers
FROM gold.dim_customers;

-- Find the total number of customers that have placed an order
SELECT 
	COUNT(DISTINCT customer_key) AS customers_orders
FROM gold.fact_sales;


-- Generate a report that shows all key metrics of the business 

SELECT 'Total Sales' AS measure_names, SUM(sales_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Quantity' AS measure_names, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Average Selling Price' AS measure_names, AVG(price) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Orders' AS measure_names, COUNT(DISTINCT order_number) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Nr. Products' AS measure_names, COUNT(product_key) AS measure_value FROM gold.dim_products
UNION ALL
SELECT 'Total Nr. Customers' AS measure_names, COUNT(customer_key) AS measure_value FROM gold.dim_customers
UNION ALL
SELECT 'Total Nr. Customers Placed Orders' AS measure_names, COUNT(DISTINCT customer_key) AS measure_value FROM gold.fact_sales;



/* ========================= 5 - Magnitude Analysis ========================= */

-- Find the total customers by countries
SELECT 
	country,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC;

-- Find the total customers by gender
SELECT
	gender,
	COUNT(customer_key) AS total_customers
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC;

-- Find the total products by category
SELECT
	category,
	COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average costs in each category?
SELECT
	category,
	AVG(cost) AS average_cost
FROM gold.dim_products
GROUP BY category
ORDER BY average_cost DESC;

-- What is the total revenue generated for each category?
SELECT
	dp.category,
	SUM(fs.sales_amount) AS total_revenue	
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.category
ORDER BY total_revenue DESC;

-- Find total revenue generated by each customer
SELECT 
	customer_key,
	SUM(price) AS total_revenue
FROM gold.fact_sales
GROUP BY customer_key
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries?
SELECT
	country,
	SUM(fs.quantity) AS total_quantity
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY country
ORDER BY total_quantity DESC;


/* ========================= 6 - Rank Analysis ========================= */

-- Which 5 products generate the highest revenue?

SELECT TOP 5
	dp.product_name,
	SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.product_name
ORDER BY total_revenue DESC;

SELECT * 
FROM (
	SELECT
		dp.product_name,
		SUM(fs.sales_amount) AS total_revenue,
		ROW_NUMBER() OVER (ORDER BY SUM(fs.sales_amount) DESC) AS rank_revenue
	FROM gold.fact_sales AS fs
	LEFT JOIN gold.dim_products AS dp
	ON fs.product_key = dp.product_key
	GROUP BY dp.product_name)t
WHERE rank_revenue <= 5;


-- What are the 5 worst-performing products in terms of sales?

SELECT TOP 5
	dp.product_name,
	SUM(fs.sales_amount) AS total_revenue
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_products AS dp
ON fs.product_key = dp.product_key
GROUP BY dp.product_name
ORDER BY total_revenue ASC;


-- Find the top 10 customers who have generated the highest revenue
SELECT *
FROM (
	SELECT 
		fs.customer_key,
		dc.first_name,
		dc.last_name,
		SUM(fs.sales_amount) AS total_revenue,
		ROW_NUMBER() OVER (ORDER BY SUM(fs.sales_amount) DESC) AS rank_customer
	FROM gold.fact_sales AS fs
	LEFT JOIN gold.dim_customers AS dc
	ON fs.customer_key = dc.customer_key
	GROUP BY fs.customer_key, dc.first_name, dc.last_name)t
WHERE rank_customer <= 10


-- The 3 customers with fewest orders placed

SELECT TOP 3
	fs.customer_key,
	dc.first_name,
	dc.last_name,
	COUNT(DISTINCT fs.order_number) AS total_orders
FROM gold.fact_sales AS fs
LEFT JOIN gold.dim_customers AS dc
ON fs.customer_key = dc.customer_key
GROUP BY 
	fs.customer_key, 
	dc.first_name, 
	dc.last_name
ORDER BY total_orders ASC
